name: Run Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the student's PR code (automatically uses the PR branch)
      - name: Checkout student PR code
        uses: actions/checkout@v2

      # Step 2: Install dependencies in the student's repo
      - name: Install dependencies in student's repo
        run: |
          cd Sprint-3/quote-generator
          npm install
          

      - name: Check environment and secrets
        run: |
          echo "Printing all environment variables"
          printenv  # This will print all the environment variables to debug
          
          echo "Checking for the RUN_CYPRESS_MODULE_DATA_GROUPS secret"
          if [ -z "${{ secret.CYPRESS }}" ]; then
            echo "CYPRESS secret is not available"
            exit 1
          else
            echo "CYPRESS secret is available"
          fi


      # Step 3: Checkout Cypress test runner repo
      - name: Checkout Cypress test runner repo
        uses: actions/checkout@v3
        with:
          repository: tyzia/moduleDataGroups_sprint3_quoteGenerator_testRunner
          token: ${{ secrets.RUN_CYPRESS_MODULE_DATA_GROUPS }}  # Ensure token is passed
          ref: main
          path: quote-generator-test-runner
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      # Step 4: Install Cypress in test runner repo
      - name: Install Cypress in test runner repo
        run: |
          cd quote-generator-test-runner
          npm install

      # Step 5: Copy exercise folder to test runner repo
      - name: Copy exercise folder to test runner repo
        run: |
          cp -r Sprint-3/quote-generator quote-generator-test-runner/

      # Step 6: Run Cypress tests inside the Sprint-3/quote-generator folder
      - name: Run Cypress tests in quote-generator
        run: |
          cd quote-generator-test-runner
          npm run cypress:run -- --spec "cypress/e2e/quote-generator/*"
