name: Run Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    environment: test-environment  # Add this line to use the environment

    steps:
      # Debug step to check if the ONE secret is accessible
      - name: Debug ONE secret
        run: |
          if [ -z "${{ secrets.CYPRESS }}" ]; then
            echo "ONE secret is empty or not found"
          else
            echo "ONE secret is set to: ${{ secrets.CYPRESS }}"
          fi